# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/


# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DEFAULT_PYTHON_VERSION: "3.9"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

# There are two stages in this pipeline: unittest and workflow
stages:
  - unit-test       # For simple unit tests
  - workflow       # For larger flows of the package
  - documentation  # For generating and checking the documentation

####################################################################################
#################################### UNIT TESTS ####################################
####################################################################################

# A template to run the different  unittests  in the different subpackages in separate jobs
.unit-test:
  stage: unit-test  # Run in `unittest`stage
  variables:
    PYTHON_VERSION: ""
  image: python:$PYTHON_VERSION
  before_script:
    - python --version ; pip --version
    - pip install -r requirements.txt
    - pip install pytest pytest-cov     # Packages for testing purposes
  script:
    # Test the requested package, print the code coverage, and generate a xml report of the tests
    - pytest ./tests/ --cov=dtaianomaly --cov-report term-missing --junitxml=report.xml -v
  coverage: '/(?i)TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 1 weeks
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $PYTHON_VERSION == $DEFAULT_PYTHON_VERSION

# Execute unit tests for multiple Python versions
#unit-test-3.6:  # Succeeds, but main script with 3.6 fails
#  extends: .unit-test
#  variables:
#    PYTHON_VERSION: "3.6"

unit-test-3.7:
  extends: .unit-test
  variables:
    PYTHON_VERSION: "3.7"

unit-test-3.8:
  extends: .unit-test
  variables:
    PYTHON_VERSION: "3.8"

unit-test-3.9:
  extends: .unit-test
  variables:
    PYTHON_VERSION: "3.9"

unit-test-3.10:
  extends: .unit-test
  variables:
    PYTHON_VERSION: "3.10"

unit-test-3.11:
  extends: .unit-test
  variables:
    PYTHON_VERSION: "3.11"

####################################################################################
##################################### WORKFLOW #####################################
####################################################################################

# A general template to run a workflow related job
.workflow:
  stage: workflow
  before_script:
    - python --version ; pip --version
    - pip install -r requirements.txt

# To easily run the main script with different versions
.workflow-main-script:
  extends: .workflow
  variables:
    PYTHON_VERSION: ""
  image: python:$PYTHON_VERSION
  script:
    - python main.py
      --data_dir data
      --datasets_index_file datasets.csv
      --configuration_dir configurations
      --data data/Demo.json
      --algorithm algorithm/iforest_64.json
      --metric metric/auc_metrics.json
      --output output/output_all.json
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
    - if: $PYTHON_VERSION == $DEFAULT_PYTHON_VERSION
    - if: $PYTHON_VERSION == ""

# Use different versions of Python
#main-script-3.6:  # Fails
#  extends: .workflow-main-script
#  variables:
#    PYTHON_VERSION: "3.6"

main-script-3.7:
  extends: .workflow-main-script
  variables:
    PYTHON_VERSION: "3.7"

main-script-3.8:
  extends: .workflow-main-script
  variables:
    PYTHON_VERSION: "3.8"

main-script-3.9:
  extends: .workflow-main-script
  variables:
    PYTHON_VERSION: "3.9"

main-script-3.10:
  extends: .workflow-main-script
  variables:
    PYTHON_VERSION: "3.10"

main-script-3.11:
  extends: .workflow-main-script
  variables:
    PYTHON_VERSION: "3.11"

# Check if the notebooks still run without any problems
# Just use the default python version, because it is time-consuming
run-notebooks:
  extends: .workflow
  variables:
    PYTHON_VERSION: $DEFAULT_PYTHON_VERSION
  script:
    - pip install jupyter
    - mv dtaianomaly notebooks
    - cd notebooks
    - jupyter nbconvert --to notebook --execute *.ipynb

####################################################################################
################################### DOCUMENTATION ##################################
####################################################################################

# A template for the documentation jobs
.documentation:
  stage: documentation
  image: python:$DEFAULT_PYTHON_VERSION-slim
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python -m pip install sphinx toml
    - cd docs

# Check the code in the documentation
doctest:
  extends: .documentation
  script:
    - make doctest

# Generate the documentation
pages:
  extends: .documentation
  script:
    - make html
  after_script:
    - mv docs/_build/html/ ./public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH