# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - unittest
  - workflow

test-notebooks:
  stage: workflow
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install -r requirements.txt
    - pip install papermill
  script:
    - echo 'STARTED script'
    - papermill notebooks/README_demo.ipynb
# Run the test suite
# test-anomaly-detection: 
#   stage: unittest
#   before_script:
#     - python --version ; pip --version  # For debugging
#     - pip install -r requirements.txt
#     - pip install pytest pytest-cov
#   script:
#     - pytest ./tests/anomaly_detection --cov=src/anomaly_detection --cov-report term-missing --junitxml=report.xml -v
#   coverage: '/(?i)TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
#   artifacts:
#     when: always
#     reports:
#       junit: report.xml
#     expire_in: 1 weeks

# Run the test suite
# test-evaluation: 
#   stage: unittest
#   before_script:
#     - python --version ; pip --version  # For debugging
#     - pip install -r requirements.txt
#     - pip install pytest pytest-cov
#   script:
#     - pytest ./tests/evaluation --cov=src/evaluation --cov-report term-missing --junitxml=report.xml -v
#   coverage: '/(?i)TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
#   artifacts:
#     when: always
#     reports:
#       junit: report.xml
#     expire_in: 1 weeks

# Check if the main script still executes without any problems
run-main-script:
  stage: workflow
  before_script:
    - python --version ; pip --version  # For debugging
    - pip install -r requirements.txt
  script:
    - python main.py